config/routes.rb
Gearshare::Application.routes.draw do
  resources :locations

  resources :friendships

  resources :items

  resources :users do
    resource :location
  end

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', :as => :sign_up

  match '/login', to: 'sessions#new', :as => :log_in

  match '/logout', to: 'sessions#destroy', :as => :log_out

  match '/auth/facebook/callback', to: 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :shared_items, :provider, :uid, :location_attributes, :image, :token

  has_many :shared_items, :class_name => "Item", :foreign_key => "owner_id"

  has_many :friendships
  has_many :friends, :through => :friendships
  #the following assoc helps a user see who has added them as friends
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

 # has_secure_password

  #validates_uniqueness_of :email
 # validates_presence_of :first_name, :last_name, :email, :on => :create

  has_one :location
  accepts_nested_attributes_for :location

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end


  def request_to_borrow_item
    self.shared_items.build(:item_id => params[:id], :status => :open)
  end

  def name
   "#{first_name}" "#{last_name}"
  end
  
  def self.create_with_omniauth(auth)
  create! do |user|
     #raise auth.inspect
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.first_name = auth["info"]["first_name"]
    user.last_name = auth["info"]["last_name"]
    user.email = auth["info"]["email"]
    user.image = auth["info"]["image"]
    user.token = auth["credentials"]["token"]

    #location is passed in as a string. need to send user.location an object.
    fblocationstr = auth["extra"]["raw_info"]["location"]["name"]
    location = Location.new
    user.location = location.location_str_to_object(fblocationstr)

    # fblocation = Location.new unless auth["extra"]["raw_info"]["location"]["name"].nil?
    # raise user.location.inspect
    # fblocation.city = = fblocation.to_a.split(,).first
    # fblocaton.state = fblocation.split(,).last
    # user.location = fbrellocation

    #user.token = auth["credentials"]["token"]
    user.save
  end

end

  
  # def self.from_omniauth(auth)
  #   user = where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  #     user.provider = auth["provider"]
  #     user.uid = auth["uid"]
  #     user.name = auth["info"]["name"]
  #     user.first_name = auth["info"]["first_name"]
  #     user.last_name = auth["info"]["last_name"]
  #     user.image = auth["info"]["image"]
  #     user.email = auth["info"]["email"]
  #     user.gender = auth["extra"]["raw_info"]["gender"]
  #     user.location = auth["extra"]["raw_info"]["location"]["name"]          
  #     user.token = auth["credentials"]["token"]
  #     end
  #   user.add_friends
  #   user.save
  #   user
  #   end

#get loop through all friends and push their attributes into the hash
  def add_friends
    # @facebook.get_connection("me", "friends").each do |hash|
    #   self.friends.where(:name => hash['name'], :uid => hash['id']).first_or_create
    # end
  end

  #Koala####

def facebook_connection
  @facebook.get_connections("me", "friends", :fields => "name, id, location")
end

#get loop through all friends and push their attributes into the hash
  # def facebook_friends
  #   facebook_connection(token).each do |hash|
  #     self.friends.where(:name => hash['name'], :uid => hash['id'], :friend_location => hash['location']).first_or_create
  #   end
  # end

#this is the query string I'm looking for... /4205423?fields=id,name,friends.fields(location)


  private

  def facebook
    @facebook ||= Koala::Facebook::API.new(token)
  end


#something like this to check if a friend of your is registered...
  # def registered_friend
  #   uids = @friends.collect(&:uid)
  #   # uids is an array of Facebook UID's, say [1234, 5678, 9012]
  #   registered_friends = User.where('fb_uid IN (?)', uids)
  #   # "SELECT users.* FROM users WHERE (fb_uid IN (1234, 5678, 9012))"
  # end

 
end



# users
# 1     Avi
# 2

# equipment       user_id
# 1     Bat       1



# shared_equipment
# id        user_id       equipment_id
# 1         2       1


# user has many owned_equipment, :class_name => "Equipment"
# equipment belongs to user
# user has many shared_equipments
# user has many equipments, through => shared_equipment


# equipment
# belongs_to :owner, :class_name => "User", :foreign_key => "user_id"



# person
# id          name          parent_id
# 1         Batsheva
# 2         Avi         1


# user belongs_to :parent, :class => User, :foreign_key => :parent_id
# user has_many 


# friendship
# user_id       friend_id
# 1         2
# 2         1

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
    @location = @user.location

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @location = @user.location
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    if @user.save
      #this allows us to login upon signup
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Gearshare!"
      redirect_to @user
    else
      render "new"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to log_out_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

 # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase) if user.email
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_form.html.erb
<%- model_class = User -%>
<!-- <div class="page-header">
  <h1><#%=t '.title', :default => model_class.model_name.human %></h1>
</div> -->

<div class="span9">

<div class="row">
  <aside class="span4">

<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  
  </div>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>

<div>
  <%= f.fields_for :location do |location_fields| %>
    Street1 : <%= location_fields.text_field :street1 %>
    City : <%= location_fields.text_field :city %>
    state: <%= location_fields.text_field :state %>
    Zip code: <%= location_fields.text_field :zip %>
  <% end %>
<div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

<% if @location %>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@user.location.latitude}%2C#{@user.location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @user.location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.to_f.round(2).to_s %> miles)</li>
<% end %>
</ul>
<% end %>
</div>
</div>
</aside>
</div>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<!-- <div class="page-header">
  <h1><#%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div> -->
<div class="span9">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:first_name) %></th>
        <th><%= model_class.human_attribute_name(:last_name) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%= model_class.human_attribute_name(:friendship) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.id, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%=l user.created_at %></td>
          <td><%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %></td>
   
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_user_path(user), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        user_path(user),
                        :method => :delete,
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<!-- <div class="page-header">
  <h1><#%=t '.title', :default => model_class.model_name.human %></h1>
</div> -->

<div class="span9">

<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%# raise @user.last_name.inspect %>
        <img src="<%= @user.image %>" alt="<%= @user.last_name %>">
        <%= @user.first_name %>
      </h1>
    </section>
  </aside>
</div>
  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
    <dd><%= @user.first_name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
    <dd><%= @user.last_name %></dd>
    
    <% if @location.street1 %>
    <dt><strong><%= model_class.human_attribute_name(:street1) %>:</strong></dt>
    <dd><%= @location.street1 %></dd>
    <% end %>

    <% if @location.city %>
    <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
    <dd><%= @location.city %></dd>
    <% end %>

    <% if @location.state %>
    <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
    <dd><%= @location.state %></dd>
    <% end %>

    <% if @location.zip %>
    <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
    <dd><%= @location.zip %></dd>
    <% end %>
  </dl>

  <div class="form-actions"> 
    <%= link_to t('.users', :default => t("helpers.links.users")),
                users_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_user_path(@user), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                user_path(@user),
                :method => 'delete',
                :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                :class => 'btn btn-danger' %>
  </div>
<% if @location %>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@user.location.latitude}%2C#{@user.location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @user.location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.to_f.round(2).to_s %> miles)</li>
<% end %>
</ul>
<% end %>
</div>