config/routes.rb
Gearshare::Application.routes.draw do
  resources :locations

  resources :friendships

  resources :items

  resources :users do
    resource :location
  end

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', :as => :sign_up

  match '/login', to: 'sessions#new', :as => :log_in

  match '/logout', to: 'sessions#destroy', :as => :log_out

  match '/auth/facebook/callback', to: 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'welcome#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :street1, :city, :state, :zip, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  

  def address
    "#{street1}, #{city}, #{state}, #{zip}"
  end

  def location_str_to_object(fb_location_as_a_string)
    self.city, self.state = fb_location_as_a_string.split(", ")
    self
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
  if params[:search].present?
    @locations = Location.near(params[:search], 50, :order => :distance)
  else
    @locations = Location.all
  end
end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = current_user.location
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

private

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%- model_class = Location -%>
<div class="span9">

<div class="row">
  <aside class="span4">
    <section>
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :street1 %><br />
    <%= f.text_field :street1 %>
  </div>
  
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</section>
</aside>
</div>
</div>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>
<%- model_class = Location -%>
<!-- <div class="page-header">
  <h1><#%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div> -->
<div class="span9">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:id) %></th>
        <th><%= model_class.human_attribute_name(:address) %></th>
        <th><%= model_class.human_attribute_name(:latitude) %></th>
        <th><%= model_class.human_attribute_name(:longitude) %></th>
        <th><%= model_class.human_attribute_name(:created_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @locations.each do |location| %>
        <tr>
          <td><%= link_to location.id, location_path(location) %></td>
          <td><%= link_to location.address, location_path(location) %></td>
          <td><%= location.latitude %></td>
          <td><%= location.longitude %></td>
          <td><%=l location.created_at %></td>
         </td>
   
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_location_path(location), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        location_path(location),
                        :method => :delete,
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_location_path,
            :class => 'btn btn-primary' %>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<%- model_class = Location -%>

<div class="span9">

<div class="row">
  <aside class="span4">

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.to_f.round(2).to_s %> miles)</li>
<% end %>
</ul>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

</aside>
</div>
</div>