config/routes.rb
Gearshare::Application.routes.draw do
  resources :locations

  resources :friendships

  resources :items

  resources :users do
    resource :location
  end

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new', :as => :sign_up

  match '/login', to: 'sessions#new', :as => :log_in

  match '/logout', to: 'sessions#destroy', :as => :log_out

  match '/auth/facebook/callback', to: 'sessions#create'
  match "/signout" => "sessions#destroy", :as => :signout

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gearshare</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

	    <div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
        <ul class="nav">
        	<a class="brand" href="/">
                Gear Share
            </a>
		  <li><a href="/items">Items List</a></li>
		  <li><a href="/users">Users gear</a></li>
		  <li><%= link_to "Sign in With Facebook", "/auth/facebook" unless current_user %></li>
		</ul>
		  
		  <script>
		 	 $(function(){
				$('.dropdown-toggle').dropdown()
		 	 })
		  </script>

			<div class="btn-group pull-right">
	          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	            	<% if current_user %>
								   	<%= current_user.first_name %>
								  <% else %>
								  	Profile
								  <% end %>
	            <span class="caret"></span>
	          </a>
	          <ul class="dropdown-menu">
	           		 	<% if current_user %>
								  	<li><%= link_to "Log out", log_out_path %></li>
								  <% else %>
								  	<li><%= link_to "Sign up", sign_up_path %></li>
								  	<li><%= link_to "Log in", log_in_path %></li>
  								<% end %>
  								<li><a href="#">Borrow gear</a></li>
		           		<li><a href="#">Action</a></li>
	         	</ul>
			  </div>

			  <form class="navbar-search pull-right">
  			<input type="text" class="search-query" placeholder="Search">
		  </form>
	    </div>
	  </div>
	</div>

</head>
<body>
<% if current_user %>
		<div class="span3">
		  <div class="well sidebar-nav">
		    <ul class="nav nav-list"> 
		      <li class="nav-header">Dashboard</li> 
		      <li><%= link_to current_user do %>
  					<i class="icon-home"></i> Profile
					<% end %></li>
		      <li><a href="/items"><i class="icon-edit"></i> Add Items</a></li>
		          <li><a href="#"><i class="icon-calendar"></i> Calendar</a></li>
		      <li><a href="#"><i class="icon-user"></i> Add Friends</a></li>
		      <li><a href="#"><i class="icon-comment"></i> Send a message</a></li>
		    </ul>
		  </div>
		</div>
								  <% end %>
<%= yield %>

</body>
</html>